# Generated by Claude - DEV-9 - 2025-11-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='forma_pagamento',
            field=models.CharField(
                blank=True, 
                choices=[
                    ('dinheiro', 'Dinheiro'), 
                    ('pix', 'PIX'), 
                    ('transferencia', 'Transferência Bancária'), 
                    ('boleto', 'Boleto'), 
                    ('cartao_credito', 'Cartão de Crédito'), 
                    ('cartao_debito', 'Cartão de Débito'), 
                    ('cheque', 'Cheque')
                ], 
                help_text='Forma de pagamento utilizada', 
                max_length=20, 
                verbose_name='Forma de Pagamento'
            ),
        ),
    ]
