# Generated by Django 4.2.8 on 2025-10-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comanda',
            old_name='juros',
            new_name='valor_juros',
        ),
        migrations.RenameField(
            model_name='comanda',
            old_name='multa',
            new_name='valor_multa',
        ),
        migrations.AlterUniqueTogether(
            name='comanda',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='comanda',
            table=None,
        ),
    ]
