# Generated by Django 4.2.8 on 2025-10-30 04:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comanda_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do aluguel no mês de referência', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Aluguel'),
        ),
    ]
