# Generated by Django 4.2.8 on 2025-10-30 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comanda_valor_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='notificacao_enviada_10dias',
            field=models.BooleanField(default=False, verbose_name='Notificação 10 dias enviada'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='notificacao_enviada_vencimento',
            field=models.BooleanField(default=False, verbose_name='Notificação dia vencimento enviada'),
        ),
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('tipo_notificacao', models.CharField(choices=[('10D', 'Lembrete 10 dias'), ('7D', 'Lembrete 7 dias'), ('1D', 'Lembrete 1 dia'), ('VEN', 'Dia do vencimento'), ('ATR1', 'Atraso 1 dia'), ('ATR7', 'Atraso 7 dias'), ('ATR14', 'Atraso 14 dias'), ('ATR21', 'Atraso 21 dias')], max_length=10, verbose_name='Tipo de Notificação')),
                ('destinatario_email', models.EmailField(max_length=254, verbose_name='Email Destinatário')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Enviado com sucesso')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_notificacao', to='core.comanda', verbose_name='Comanda')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
