# Generated by Django 4.2.8 on 2025-11-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comanda_notificacao_enviada_10dias_and_more'),
        ('core', '0005_make_usuario_registro_nullable'),
    ]

    operations = [
    ]
