# Generated by Django 4.2.8 on 2025-09-30 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_configuracaofinanceira_delete_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('numero_pagamento', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número do Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('boleto', 'Boleto'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('cheque', 'Cheque')], max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=20, verbose_name='Status')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.comanda', verbose_name='Comanda')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Registrou')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'core_pagamento',
                'ordering': ['-data_pagamento', '-created_at'],
            },
        ),
    ]
