# Generated by Django 4.2.8 on 2025-11-04 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251104_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=20, unique=True)),
                ('current_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Sequência',
                'verbose_name_plural': 'Contadores de Sequência',
                'db_table': 'core_sequence_counter',
            },
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='usuario_registro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Registrou'),
            preserve_default=False,
        ),
    ]
