# Generated by Django 4.2.8 on 2025-11-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sequencecounter_alter_pagamento_usuario_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quitado_em', models.DateTimeField(blank=True, null=True)),
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_info', to='core.comanda')),
            ],
            options={
                'verbose_name': 'Comanda Status',
                'verbose_name_plural': 'Comandas Status',
            },
        ),
    ]
