# Generated by Django 4.2.8 on 2025-09-30 16:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_templatecontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecontrato',
            name='arquivo_template',
            field=models.FileField(help_text='Formatos aceitos: .docx (Word) ou .odt (LibreOffice)', upload_to='templates_contratos/', validators=[core.models.validar_arquivo_template], verbose_name='Arquivo do Template'),
        ),
    ]
