# Generated by Django 4.2.8 on 2025-11-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comanda_forma_pagamento'),
        ('core', '0008_comandastatus'),
    ]

    operations = [
    ]
