# Generated by Django 4.2.8 on 2025-10-01 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_loggeracaocomandas_configuracaosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='mes_referencia',
            field=models.DateField(help_text='Mês de referência da cobrança (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês de Referência'),
        ),
    ]
