# Generated by Django 4.2.8 on 2025-11-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251112_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificacaoLog',
        ),
    ]
