# Generated by Django - HABITAT PRO Melhoria 3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_notificacaolog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='valor_aluguel',
            new_name='_valor_aluguel_historico',
        ),
    ]
