# Generated by Django 4.2.8 on 2025-11-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_valor_aluguel_to_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='_valor_aluguel_historico',
            field=models.DecimalField(decimal_places=2, help_text='Valor do aluguel no momento da geração (histórico)', max_digits=10, verbose_name='Valor Aluguel (Histórico)'),
        ),
    ]
