# Generated by Django 4.2.8 on 2025-10-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracaosistema_percentual_juros_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='notificacao_atraso_enviada',
            field=models.BooleanField(default=False, verbose_name='Notificação de atraso enviada'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='notificacao_enviada_1dia',
            field=models.BooleanField(default=False, verbose_name='Notificação 1 dia enviada'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='notificacao_enviada_7dias',
            field=models.BooleanField(default=False, verbose_name='Notificação 7 dias enviada'),
        ),
    ]
