# Generated by Django 4.2.8 on 2025-10-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_locacao_dia_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='mes_referencia',
            field=models.DateField(help_text='Primeiro dia do mês de referência (formato YYYY-MM-01)', verbose_name='Mês de Referência'),
        ),
    ]
