# Generated by Django 4.2.8 on 2025-12-27 19:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_locacao_garantias_dev20'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenovacaoContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nova_data_inicio', models.DateField(help_text='Início da nova vigência', verbose_name='Nova Data de Início')),
                ('nova_data_fim', models.DateField(help_text='Fim da nova vigência', verbose_name='Nova Data de Fim')),
                ('novo_valor_aluguel', models.DecimalField(decimal_places=2, help_text='Valor mensal proposto para o novo contrato', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Novo Valor do Aluguel')),
                ('nova_duracao_meses', models.IntegerField(default=12, help_text='Duração da nova vigência em meses', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Duração (meses)')),
                ('novo_tipo_garantia', models.CharField(choices=[('fiador', 'Fiador'), ('caucao', 'Caução'), ('seguro', 'Seguro Garantia'), ('nenhuma', 'Sem Garantia')], default='nenhuma', help_text='Tipo de garantia para o contrato renovado', max_length=20, verbose_name='Tipo de Garantia (Novo Contrato)')),
                ('nova_caucao_meses', models.IntegerField(blank=True, help_text='Quantidade de meses de aluguel como caução', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Nova Caução (quantidade de meses)')),
                ('nova_caucao_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total da caução (calculado automaticamente)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Nova Caução (valor total)')),
                ('nova_seguro_apolice', models.CharField(blank=True, help_text='Número da apólice do seguro garantia', max_length=100, verbose_name='Nova Apólice de Seguro')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente_proprietario', 'Aguardando Proprietário'), ('pendente_locatario', 'Aguardando Locatário'), ('aprovada', 'Aprovada - Aguardando Vigência'), ('ativa', 'Ativa (Novo Contrato Gerado)'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='rascunho', help_text='Status atual do processo de renovação', max_length=30, verbose_name='Status')),
                ('data_proposta', models.DateTimeField(auto_now_add=True, help_text='Quando a proposta foi criada', verbose_name='Data da Proposta')),
                ('proprietario_aprovou', models.BooleanField(blank=True, help_text='True=Aprovado, False=Rejeitado, None=Pendente', null=True, verbose_name='Proprietário Aprovou?')),
                ('data_aprovacao_proprietario', models.DateTimeField(blank=True, null=True, verbose_name='Data Aprovação Proprietário')),
                ('ip_aprovacao_proprietario', models.GenericIPAddressField(blank=True, help_text='Endereço IP de onde a aprovação foi feita', null=True, verbose_name='IP Aprovação Proprietário')),
                ('token_proprietario', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para link de aprovação do proprietário', unique=True, verbose_name='Token Proprietário')),
                ('locatario_aprovou', models.BooleanField(blank=True, help_text='True=Aprovado, False=Rejeitado, None=Pendente', null=True, verbose_name='Locatário Aprovou?')),
                ('data_aprovacao_locatario', models.DateTimeField(blank=True, null=True, verbose_name='Data Aprovação Locatário')),
                ('ip_aprovacao_locatario', models.GenericIPAddressField(blank=True, help_text='Endereço IP de onde a aprovação foi feita', null=True, verbose_name='IP Aprovação Locatário')),
                ('token_locatario', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para link de aprovação do locatário', unique=True, verbose_name='Token Locatário')),
                ('aprovacao_manual_proprietario', models.BooleanField(default=False, help_text='Marcado quando aprovação feita por telefone/presencial', verbose_name='✋ Aprovação Manual Proprietário')),
                ('aprovacao_manual_locatario', models.BooleanField(default=False, help_text='Marcado quando aprovação feita por telefone/presencial', verbose_name='✋ Aprovação Manual Locatário')),
                ('motivo_aprovacao_manual', models.TextField(blank=True, help_text='Justificativa para aprovação manual (ex: sem internet)', verbose_name='Motivo Aprovação Manual')),
                ('contrato_gerado', models.FileField(blank=True, help_text='Arquivo do novo contrato gerado', null=True, upload_to='contratos/renovacoes/', verbose_name='Contrato Gerado (DOCX/PDF)')),
                ('data_geracao_contrato', models.DateTimeField(blank=True, null=True, verbose_name='Data Geração Contrato')),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre o processo de renovação', verbose_name='Observações')),
                ('motivo_recusa', models.TextField(blank=True, help_text='Se recusada, explicar o motivo', verbose_name='Motivo da Recusa')),
                ('historico_comunicacoes', models.JSONField(blank=True, default=dict, help_text='Log de emails/WhatsApp enviados', verbose_name='Histórico de Comunicações')),
                ('locacao_original', models.ForeignKey(help_text='Contrato que está sendo renovado', on_delete=django.db.models.deletion.CASCADE, related_name='propostas_renovacao', to='core.locacao', verbose_name='Locação Original')),
                ('nova_locacao', models.OneToOneField(blank=True, help_text='Locação criada após aprovação da renovação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_renovacao', to='core.locacao', verbose_name='Nova Locação Gerada')),
                ('novo_fiador', models.ForeignKey(blank=True, help_text='Fiador para o contrato renovado (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes_como_fiador', to='core.fiador', verbose_name='Novo Fiador')),
            ],
            options={
                'verbose_name': 'Renovação de Contrato',
                'verbose_name_plural': 'Renovações de Contratos',
                'ordering': ['-data_proposta'],
                'indexes': [models.Index(fields=['status'], name='core_renova_status_e07c5e_idx'), models.Index(fields=['locacao_original', 'status'], name='core_renova_locacao_1fb069_idx'), models.Index(fields=['data_proposta'], name='core_renova_data_pr_af5d0b_idx')],
            },
        ),
    ]
