# Generated by Django - DEV_21.6 - Tokens públicos (PARTE 1)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_renovacao_contratos_dev21'),
    ]

    operations = [
        # ════════════════════════════════════════════════════════════
        # PARTE 1: Adicionar campos SEM unique constraint
        # ════════════════════════════════════════════════════════════
        
        # COMANDA
        migrations.AddField(
            model_name='comanda',
            name='token',
            field=models.UUIDField(
                null=True,  # Temporário
                blank=True,
                editable=False,
                help_text='Token público para acesso sem autenticação'
            ),
        ),
        migrations.AddField(
            model_name='comanda',
            name='token_gerado_em',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Data/hora de geração do token'
            ),
        ),
        migrations.AddField(
            model_name='comanda',
            name='token_expira_em',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Data/hora de expiração do token (30 dias)'
            ),
        ),
        
        # PAGAMENTO
        migrations.AddField(
            model_name='pagamento',
            name='token',
            field=models.UUIDField(
                null=True,  # Temporário
                blank=True,
                editable=False,
                help_text='Token público para acesso ao recibo'
            ),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='token_gerado_em',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Data/hora de geração do token'
            ),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='token_expira_em',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Data/hora de expiração do token (30 dias)'
            ),
        ),
        
        # RENOVACAO
        migrations.AddField(
            model_name='renovacaocontrato',
            name='token_gerado_em',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Data/hora de geração dos tokens'
            ),
        ),
        migrations.AddField(
            model_name='renovacaocontrato',
            name='token_expira_em',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Data/hora de expiração dos tokens (30 dias)'
            ),
        ),
    ]
