# Generated by Django 4.2.8 on 2025-10-19 02:25

import core.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_comanda_mes_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome_completo', models.CharField(help_text='Nome completo do fiador', max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(help_text='CPF do fiador (formato: 000.000.000-00)', max_length=14, unique=True, validators=[core.models.validate_cpf], verbose_name='CPF')),
                ('rg', models.CharField(help_text='Exemplo: 109521205 SESP PR', max_length=50, verbose_name='RG')),
                ('data_nascimento', models.DateField(help_text='Data de nascimento do fiador', verbose_name='Data de Nascimento')),
                ('nome_pai', models.CharField(blank=True, help_text='Nome completo do pai', max_length=200, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, help_text='Nome completo da mãe', max_length=200, verbose_name='Nome da Mãe')),
                ('telefone', models.CharField(help_text='Telefone principal de contato', max_length=20, verbose_name='Telefone Principal')),
                ('email', models.EmailField(help_text='E-mail principal de contato', max_length=254, verbose_name='E-mail')),
                ('outro_telefone', models.CharField(blank=True, help_text='Telefone secundário', max_length=20, verbose_name='Outro Telefone')),
                ('nome_contato_emergencia', models.CharField(blank=True, help_text='Nome completo do contato', max_length=200, verbose_name='Nome do Contato de Emergência')),
                ('telefone_contato_emergencia', models.CharField(blank=True, help_text='Telefone do contato', max_length=20, verbose_name='Telefone do Contato de Emergência')),
                ('endereco_completo', models.TextField(help_text='Endereço completo do fiador', verbose_name='Endereço Completo')),
                ('cep', models.CharField(help_text='CEP no formato 12345-678', max_length=9, verbose_name='CEP')),
                ('empresa_trabalho', models.CharField(blank=True, help_text='Nome da empresa onde trabalha', max_length=200, verbose_name='Empresa/Trabalho')),
                ('endereco_empresa', models.TextField(blank=True, help_text='Endereço completo da empresa', verbose_name='Endereço da Empresa')),
                ('telefone_empresa', models.CharField(blank=True, help_text='Telefone da empresa', max_length=20, verbose_name='Telefone da Empresa')),
                ('contato_empresa', models.CharField(blank=True, help_text='Nome do contato/supervisor na empresa', max_length=200, verbose_name='Contato na Empresa')),
                ('tempo_empresa', models.CharField(blank=True, help_text='Exemplo: 2 anos e 3 meses', max_length=50, verbose_name='Tempo na Empresa')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Renda mensal declarada', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Renda Mensal')),
            ],
            options={
                'verbose_name': 'Fiador',
                'verbose_name_plural': 'Fiadores',
                'db_table': 'core_fiador',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='conta_agua_esgoto',
            field=models.CharField(blank=True, help_text='Exemplo: 50683-4', max_length=50, verbose_name='Conta de Água/Esgoto'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_hidrometro',
            field=models.CharField(blank=True, help_text='Exemplo: Y19S381570', max_length=50, verbose_name='Número do Hidrômetro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='unidade_consumidora_energia',
            field=models.CharField(blank=True, help_text='Exemplo: 84829729', max_length=50, verbose_name='Unidade Consumidora de Energia'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='contato_empresa',
            field=models.CharField(blank=True, help_text='Nome do contato/supervisor na empresa', max_length=200, verbose_name='Contato na Empresa'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento do locatário', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='empresa_trabalho',
            field=models.CharField(blank=True, help_text='Nome da empresa onde trabalha', max_length=200, verbose_name='Empresa/Trabalho'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='endereco_empresa',
            field=models.TextField(blank=True, help_text='Endereço completo da empresa', verbose_name='Endereço da Empresa'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='nome_contato_emergencia',
            field=models.CharField(blank=True, help_text='Nome completo do contato', max_length=200, verbose_name='Nome do Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='nome_mae',
            field=models.CharField(blank=True, help_text='Nome completo da mãe', max_length=200, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='nome_pai',
            field=models.CharField(blank=True, help_text='Nome completo do pai', max_length=200, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='outro_telefone',
            field=models.CharField(blank=True, help_text='Telefone secundário', max_length=20, verbose_name='Outro Telefone'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='rg',
            field=models.CharField(blank=True, help_text='Exemplo: 109521205 SESP PR', max_length=50, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='telefone_contato_emergencia',
            field=models.CharField(blank=True, help_text='Telefone do contato', max_length=20, verbose_name='Telefone do Contato de Emergência'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='telefone_empresa',
            field=models.CharField(blank=True, help_text='Telefone da empresa', max_length=20, verbose_name='Telefone da Empresa'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='tempo_empresa',
            field=models.CharField(blank=True, help_text='Exemplo: 2 anos e 3 meses', max_length=50, verbose_name='Tempo na Empresa'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='numero_contrato',
            field=models.CharField(blank=True, help_text='Gerado automaticamente: YYYYMM + 6 dígitos CPF + código imóvel', max_length=50, unique=True, verbose_name='Número do Contrato'),
        ),
        migrations.AddField(
            model_name='locatario',
            name='fiador',
            field=models.ForeignKey(blank=True, help_text='Fiador/Garantidor do locatário (se houver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locatarios_afiancados', to='core.fiador', verbose_name='Fiador'),
        ),
    ]
