# Generated by Django - DEV_21.6 - Tokens públicos (PARTE 2)

from django.db import migrations, models
import uuid


def gerar_tokens_unicos(apps, schema_editor):
    """
    Gera tokens ÚNICOS para cada registro existente.
    """
    from datetime import timedelta
    from django.utils import timezone
    
    Comanda = apps.get_model('core', 'Comanda')
    Pagamento = apps.get_model('core', 'Pagamento')
    RenovacaoContrato = apps.get_model('core', 'RenovacaoContrato')
    
    agora = timezone.now()
    expiracao = agora + timedelta(days=30)
    
    # Comandas - gerar UUID único para cada uma
    print(f"\n🔄 Gerando tokens para {Comanda.objects.count()} comandas...")
    for comanda in Comanda.objects.all():
        comanda.token = uuid.uuid4()
        comanda.token_gerado_em = agora
        comanda.token_expira_em = expiracao
        comanda.save(update_fields=['token', 'token_gerado_em', 'token_expira_em'])
    
    # Pagamentos - gerar UUID único para cada um
    print(f"🔄 Gerando tokens para {Pagamento.objects.count()} pagamentos...")
    for pagamento in Pagamento.objects.all():
        pagamento.token = uuid.uuid4()
        pagamento.token_gerado_em = agora
        pagamento.token_expira_em = expiracao
        pagamento.save(update_fields=['token', 'token_gerado_em', 'token_expira_em'])
    
    # Renovações - apenas datas (tokens já existem)
    print(f"🔄 Atualizando {RenovacaoContrato.objects.count()} renovações...")
    for renovacao in RenovacaoContrato.objects.all():
        renovacao.token_gerado_em = agora
        renovacao.token_expira_em = expiracao
        renovacao.save(update_fields=['token_gerado_em', 'token_expira_em'])
    
    print("✅ Tokens gerados com sucesso!\n")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tokens_publicos_parte1'),
    ]

    operations = [
        # ════════════════════════════════════════════════════════════
        # PARTE 2: Preencher tokens + adicionar unique constraint
        # ════════════════════════════════════════════════════════════
        
        # Gerar tokens únicos para registros existentes
        migrations.RunPython(
            gerar_tokens_unicos,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Agora adicionar unique constraint
        migrations.AlterField(
            model_name='comanda',
            name='token',
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                help_text='Token público para acesso sem autenticação'
            ),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='token',
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                help_text='Token público para acesso ao recibo'
            ),
        ),
    ]
