# Generated by Django 4.2.8 on 2026-01-02 03:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tokens_publicos_parte2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token público para acesso sem autenticação (expira em 30 dias)', unique=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='token_expira_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora de expiração do token', null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token público para acesso ao recibo (expira em 30 dias)', unique=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='token_expira_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora de expiração do token', null=True),
        ),
        migrations.CreateModel(
            name='ContratoDownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token UUID único para acesso seguro', unique=True)),
                ('tipo_destinatario', models.CharField(choices=[('locatario', 'Locatário'), ('proprietario', 'Proprietário')], default='locatario', help_text='Destinatário do link', max_length=20)),
                ('expira_em', models.DateTimeField(help_text='Data/hora de expiração do token (7 dias padrão)')),
                ('acessos', models.IntegerField(default=0, help_text='Número total de downloads realizados')),
                ('ultimo_acesso', models.DateTimeField(blank=True, help_text='Data/hora do último acesso', null=True)),
                ('ip_acessos', models.JSONField(blank=True, default=list, help_text='Log de IPs que acessaram o link')),
                ('renovacao', models.ForeignKey(help_text='Renovação de contrato associada', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_download', to='core.renovacaocontrato')),
            ],
            options={
                'verbose_name': 'Token de Download de Contrato',
                'verbose_name_plural': 'Tokens de Download de Contratos',
                'db_table': 'core_contrato_download_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='core_contra_token_ac5560_idx'), models.Index(fields=['expira_em'], name='core_contra_expira__85fc82_idx')],
            },
        ),
    ]
