# Generated by Django 4.2.8 on 2025-10-23 03:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_locador_representante'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=20)),
                ('destinatario', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ERRO', 'Erro'), ('PENDENTE', 'Pendente')], max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.comanda')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-data_envio'],
            },
        ),
    ]
