# Generated by Django 4.2.8 on 2026-01-12 00:13

import core.models_inspection
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_comanda_token_alter_comanda_token_expira_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Ex: Vistoria de Entrada, Vistoria de Saída', max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Observações gerais sobre a vistoria', null=True, verbose_name='Descrição/Observações')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Status')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='Token de Acesso')),
                ('token_expires_at', models.DateTimeField(help_text='Data de expiração do token de acesso', verbose_name='Token Expira Em')),
                ('inspector_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Inspector')),
                ('inspector_contato', models.CharField(blank=True, help_text='Telefone ou email', max_length=20, null=True, verbose_name='Contato do Inspector')),
                ('scheduled_at', models.DateTimeField(auto_now_add=True, verbose_name='Agendada Em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada Em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída Em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='core.locacao', verbose_name='Contrato')),
                ('renovacao', models.ForeignKey(blank=True, help_text='Se esta vistoria foi feita por causa de uma renovação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistorias', to='core.renovacaocontrato', verbose_name='Renovação Relacionada')),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to=core.models_inspection.upload_inspection_pdf_path, verbose_name='Arquivo PDF')),
                ('paginas', models.PositiveIntegerField(verbose_name='Número de Páginas')),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='Gerado Em')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='core.inspection', verbose_name='Vistoria')),
            ],
            options={
                'verbose_name': 'PDF de Vistoria',
                'verbose_name_plural': 'PDFs de Vistoria',
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to=core.models_inspection.upload_inspection_photo_path, verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, help_text='Ex: Sala - Parede norte', max_length=200, verbose_name='Legenda')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem de exibição no relatório', verbose_name='Ordem')),
                ('largura', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largura (px)')),
                ('altura', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura (px)')),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('tirada_em', models.DateTimeField(auto_now_add=True, verbose_name='Tirada Em')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.inspection', verbose_name='Vistoria')),
            ],
            options={
                'verbose_name': 'Foto de Vistoria',
                'verbose_name_plural': 'Fotos de Vistoria',
                'ordering': ['ordem', 'tirada_em'],
                'indexes': [models.Index(fields=['inspection', 'ordem'], name='core_inspec_inspect_aaf1cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['token'], name='core_inspec_token_cd85a5_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='core_inspec_status_9699f5_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['-created_at'], name='core_inspec_created_1ef2c2_idx'),
        ),
    ]
