# Generated by Django 4.2.8 on 2026-02-12 01:33

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_inspection_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratodownloadtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token de Download de Contrato', 'verbose_name_plural': '🔄 2.3 Renovações de Contratos'},
        ),
        migrations.AddField(
            model_name='locacao',
            name='data_rescisao',
            field=models.DateField(blank=True, help_text='Data efetiva da rescisão do contrato', null=True, verbose_name='Data de Rescisão'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('PENDING', 'Pendente'), ('EXPIRED', 'Vencida'), ('RESCINDED', 'Rescindido')], default='PENDING', help_text='Status atual do contrato', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='RescisaoContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('LOCATARIO', 'Por Iniciativa do Locatário'), ('LOCADOR', 'Por Iniciativa do Locador'), ('CONSENSUAL', 'Consensual'), ('JUDICIAL', 'Judicial')], help_text='Quem está solicitando a rescisão', max_length=20, verbose_name='Tipo de Rescisão')),
                ('motivo', models.CharField(choices=[('INADIMPLENCIA', 'Inadimplência'), ('DESOCUPACAO', 'Desocupação Voluntária'), ('DESCUMPRIMENTO', 'Descumprimento Contratual'), ('FIM_PRAZO', 'Fim do Prazo Determinado'), ('OUTRO', 'Outro Motivo')], help_text='Motivo da rescisão', max_length=20, verbose_name='Motivo')),
                ('data_solicitacao', models.DateField(auto_now_add=True, help_text='Data em que foi solicitada a rescisão', verbose_name='Data de Solicitação')),
                ('data_desocupacao', models.DateField(help_text='Data prevista/efetiva de desocupação do imóvel', verbose_name='Data de Desocupação')),
                ('data_vistoria', models.DateField(blank=True, help_text='Data em que foi realizada a vistoria de saída', null=True, verbose_name='Data da Vistoria')),
                ('status', models.CharField(choices=[('SOLICITADA', '📝 Solicitada'), ('EM_ANALISE', '🔍 Em Análise'), ('APROVADA', '✅ Aprovada'), ('VISTORIA_AGENDADA', '📅 Vistoria Agendada'), ('VISTORIA_REALIZADA', '🏠 Vistoria Realizada'), ('DOCUMENTOS_GERADOS', '📄 Documentos Gerados'), ('AGUARDANDO_PAGAMENTO', '⏳ Aguardando Pagamento'), ('FINALIZADA', '🏁 Finalizada'), ('CANCELADA', '❌ Cancelada')], default='SOLICITADA', help_text='Status atual do processo de rescisão', max_length=30, verbose_name='Status')),
                ('observacoes_solicitacao', models.TextField(blank=True, help_text='Observações informadas ao solicitar rescisão', verbose_name='Observações da Solicitação')),
                ('observacoes_vistoria', models.TextField(blank=True, help_text='Observações da vistoria de saída', verbose_name='Observações da Vistoria')),
                ('imovel_conforme', models.BooleanField(blank=True, help_text='Se imóvel está nas mesmas condições da entrada', null=True, verbose_name='Imóvel Conforme')),
                ('avarias_detectadas', models.TextField(blank=True, help_text='Descrição detalhada das avarias encontradas', verbose_name='Avarias Detectadas')),
                ('custo_reparos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor estimado para reparos necessários', max_digits=10, verbose_name='Custo de Reparos')),
                ('multa_rescisoria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Multa por rescisão antecipada (ex: 3 aluguéis)', max_digits=10, verbose_name='Multa Rescisória')),
                ('valor_aluguel_proporcional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aluguel proporcional aos dias ocupados', max_digits=10, verbose_name='Aluguel Proporcional')),
                ('valor_agua', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Conta de água pendente', max_digits=10, verbose_name='Valor Água')),
                ('valor_luz', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Conta de luz pendente', max_digits=10, verbose_name='Valor Luz')),
                ('valor_gas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Conta de gás pendente', max_digits=10, verbose_name='Valor Gás')),
                ('valor_condominio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Condomínio pendente', max_digits=10, verbose_name='Valor Condomínio')),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outras despesas pendentes', max_digits=10, verbose_name='Outras Despesas')),
                ('valor_caucao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor da caução a ser deduzido do total devido', max_digits=10, verbose_name='Valor Caução (deduzir)')),
                ('valor_total_devido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total devido na rescisão', max_digits=10, verbose_name='Total Devido')),
                ('valor_total_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total já pago', max_digits=10, verbose_name='Total Pago')),
                ('quantidade_parcelas', models.IntegerField(default=1, help_text='Número de parcelas acordado', verbose_name='Quantidade de Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de cada parcela', max_digits=10, verbose_name='Valor da Parcela')),
                ('termo_recebimento_chaves', models.FileField(blank=True, help_text='Documento Word gerado automaticamente', null=True, upload_to='rescisoes/termos/', verbose_name='Termo de Recebimento de Chaves')),
                ('laudo_vistoria', models.FileField(blank=True, help_text='Laudo da vistoria de saída', null=True, upload_to='rescisoes/vistorias/', verbose_name='Laudo de Vistoria')),
                ('log_solicitacao', models.JSONField(blank=True, default=dict, help_text='Log detalhado da solicitação inicial', verbose_name='Log de Solicitação')),
                ('log_confirmacao_inquilino', models.JSONField(blank=True, default=dict, help_text='Log da confirmação via link público', verbose_name='Log de Confirmação do Inquilino')),
                ('log_vistoria', models.JSONField(blank=True, default=dict, help_text='Registro completo da vistoria', verbose_name='Log de Vistoria')),
                ('log_comunicacoes', models.JSONField(blank=True, default=list, help_text='Histórico completo de emails/WhatsApp enviados', verbose_name='Log de Comunicações')),
                ('token_confirmacao', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token para inquilino confirmar rescisão', unique=True, verbose_name='Token de Confirmação')),
                ('token_confirmacao_expira', models.DateTimeField(blank=True, help_text='Data de expiração do token (7 dias padrão)', null=True, verbose_name='Token Expira Em')),
                ('data_confirmacao_inquilino', models.DateTimeField(blank=True, help_text='Quando inquilino confirmou via link', null=True, verbose_name='Data Confirmação Inquilino')),
                ('confirmado_por_inquilino', models.BooleanField(default=False, help_text='Se inquilino confirmou a rescisão', verbose_name='Confirmado pelo Inquilino')),
                ('locacao', models.ForeignKey(help_text='Contrato de locação que está sendo rescindido', on_delete=django.db.models.deletion.PROTECT, related_name='rescisoes', to='core.locacao', verbose_name='Locação')),
                ('solicitante', models.ForeignKey(help_text='Usuário do sistema que registrou a solicitação', on_delete=django.db.models.deletion.PROTECT, related_name='rescisoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Rescisão de Contrato',
                'verbose_name_plural': '🔄 3.1 Rescisões de Contratos',
                'db_table': 'core_rescisao_contrato',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ComandaRescisao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('numero_parcela', models.IntegerField(help_text='Número sequencial da parcela', verbose_name='Número da Parcela')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor total da parcela', max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(help_text='Data de vencimento do pagamento', verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data em que foi efetivamente pago', null=True, verbose_name='Data de Pagamento')),
                ('descricao', models.CharField(help_text='Descrição da cobrança', max_length=200, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', help_text='Status atual da comanda', max_length=20, verbose_name='Status')),
                ('comprovante', models.FileField(blank=True, help_text='Comprovante de pagamento', null=True, upload_to='comprovantes/', verbose_name='Comprovante')),
                ('gateway_payment_id', models.CharField(blank=True, help_text='ID do pagamento no gateway (Asaas/Mercado Pago)', max_length=100, verbose_name='ID Gateway')),
                ('pix_qrcode', models.TextField(blank=True, help_text='Código PIX para pagamento', verbose_name='QR Code PIX')),
                ('boleto_url', models.URLField(blank=True, help_text='Link para boleto bancário', verbose_name='URL Boleto')),
                ('notificacao_enviada', models.BooleanField(default=False, help_text='Se notificação de cobrança foi enviada', verbose_name='Notificação Enviada')),
                ('data_notificacao', models.DateTimeField(blank=True, help_text='Quando foi enviada a notificação', null=True, verbose_name='Data Notificação')),
                ('notificacao_atraso_enviada', models.BooleanField(default=False, help_text='Se notificação de atraso foi enviada', verbose_name='Notificação Atraso Enviada')),
                ('data_notificacao_atraso', models.DateTimeField(blank=True, help_text='Quando foi enviada notificação de atraso', null=True, verbose_name='Data Notificação Atraso')),
                ('token_publico', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token UUID para acesso público sem login', unique=True, verbose_name='Token Público')),
                ('token_expira_em', models.DateTimeField(blank=True, help_text='Data de expiração do token público', null=True, verbose_name='Token Expira Em')),
                ('token_acessos', models.IntegerField(default=0, help_text='Quantidade de vezes que o token foi acessado', verbose_name='Acessos ao Token')),
                ('token_ultimo_acesso', models.DateTimeField(blank=True, help_text='Data/hora do último acesso ao token', null=True, verbose_name='Último Acesso Token')),
                ('rescisao', models.ForeignKey(help_text='Rescisão de contrato associada', on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='core.rescisaocontrato', verbose_name='Rescisão')),
            ],
            options={
                'verbose_name': 'Comanda de Rescisão',
                'verbose_name_plural': '🔄 3.2 Comandas de Rescisões',
                'db_table': 'core_comanda_rescisao',
                'ordering': ['numero_parcela'],
            },
        ),
        migrations.AddIndex(
            model_name='rescisaocontrato',
            index=models.Index(fields=['status'], name='core_rescis_status_67b434_idx'),
        ),
        migrations.AddIndex(
            model_name='rescisaocontrato',
            index=models.Index(fields=['data_desocupacao'], name='core_rescis_data_de_5a400d_idx'),
        ),
        migrations.AddIndex(
            model_name='rescisaocontrato',
            index=models.Index(fields=['tipo'], name='core_rescis_tipo_570ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='rescisaocontrato',
            index=models.Index(fields=['token_confirmacao'], name='core_rescis_token_c_2b332a_idx'),
        ),
        migrations.AddIndex(
            model_name='comandarescisao',
            index=models.Index(fields=['status'], name='core_comand_status_bd284d_idx'),
        ),
        migrations.AddIndex(
            model_name='comandarescisao',
            index=models.Index(fields=['data_vencimento'], name='core_comand_data_ve_ba7143_idx'),
        ),
        migrations.AddIndex(
            model_name='comandarescisao',
            index=models.Index(fields=['token_publico'], name='core_comand_token_p_a0cbb6_idx'),
        ),
    ]
