# Generated by Django 4.2.8 on 2026-02-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0020_pagamento_polimorfico'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagamento',
            new_name='core_pagame_content_d17205_idx',
            old_name='pag_poly_idx',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.comanda', verbose_name='Comanda'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de comanda (Comanda ou ComandaRescisao)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Comanda'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='object_id',
            field=models.UUIDField(blank=True, help_text='ID genérico da comanda associada', null=True, verbose_name='ID da Comanda'),
        ),
    ]
