# Generated by Django 4.2.8 on 2026-02-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pagamento_polimorfico_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandarescisao',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Soma de todos os pagamentos confirmados desta comanda', max_digits=10, verbose_name='Valor Pago'),
        ),
    ]
