# Generated by Django 4.2.8 on 2025-09-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaofinanceira_pagamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoFinanceira',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
