# Generated by Django 4.2.8 on 2025-09-30 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do registro', verbose_name='Data de Atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (soft delete)', verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo_template', models.FileField(upload_to='templates_contratos/', verbose_name='Arquivo do Template (.docx)')),
                ('tipo_imovel', models.CharField(blank=True, choices=[('APARTMENT', 'Apartamento'), ('HOUSE', 'Casa'), ('COMMERCIAL', 'Comercial'), ('LAND', 'Terreno'), ('WAREHOUSE', 'Galpão'), ('OFFICE', 'Sala'), ('STORE', 'Loja')], help_text='Se preenchido, este template será usado para este tipo', max_length=20, verbose_name='Tipo de Imóvel')),
                ('is_default', models.BooleanField(default=False, help_text='Usar como template padrão quando não houver específico', verbose_name='Template Padrão')),
                ('locador', models.ForeignKey(blank=True, help_text='Se preenchido, este template será usado para este locador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_contrato', to='core.locador', verbose_name='Locador Específico')),
            ],
            options={
                'verbose_name': 'Template de Contrato',
                'verbose_name_plural': 'Templates de Contratos',
                'db_table': 'core_template_contrato',
                'ordering': ['-is_default', 'nome'],
            },
        ),
    ]
