# Generated by Django 4.2.8 on 2025-10-01 04:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_templatecontrato_arquivo_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogGeracaoComandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('mes_referencia', models.DateField(help_text='Mês/ano de referência (YYYY-MM-01)')),
                ('comandas_geradas', models.IntegerField(default=0)),
                ('comandas_duplicadas', models.IntegerField(default=0)),
                ('locacoes_processadas', models.IntegerField(default=0)),
                ('sucesso', models.BooleanField(default=True)),
                ('mensagem', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('executado_por', models.CharField(default='Sistema', help_text='manual, cron, celery, sistema', max_length=50)),
            ],
            options={
                'verbose_name': 'Log de Geração de Comandas',
                'verbose_name_plural': 'Logs de Geração de Comandas',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_vencimento_padrao', models.IntegerField(default=10, help_text='Dia do mês para vencimento das comandas (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('gerar_comandas_automaticamente', models.BooleanField(default=True, help_text='Gerar comandas automaticamente todo mês')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
