# Generated by Django 4.2.8 on 2025-10-02 00:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comanda_mes_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='percentual_juros_mensal',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Percentual de juros ao mês (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='percentual_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentual de multa por atraso (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
