# Generated by Django 4.2.8 on 2025-10-06 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_comanda_notificacao_atraso_enviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='dia_vencimento',
            field=models.IntegerField(default=10, help_text='Dia do mês para vencimento da comanda (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento'),
        ),
    ]
