# Generated by Django 4.2.8 on 2025-10-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fiador_imovel_conta_agua_esgoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locador',
            name='representante',
            field=models.CharField(blank=True, help_text='Nome do representante legal do locador', max_length=200, verbose_name='Representante'),
        ),
    ]
